= SGPF
Paulo Borges (C);
:revnumber: {version}
:revdate: {localdate}
:toc: 
:toc-placement!:
:sectnums:                                                          
:toclevels: 4 	
:toc-title: Indice	
:experimental:                                                      
:description:                             
:keywords: ISEL MEIC                                            
:imagesdir: ./img 	

NOTE: Last update: 2018-11-30. Generate: {localdate} {localtime}


[[doc.summary]]
== Sumario


== Sobre
Instituição: ISEL
Curso: MEIC
Disciplina: Engenharia de Software
Ano Lectivo: __


== Elementos de grupo:

* Paulo Borges
* João Iber da Costa

== Prazos 

Datas limites das sub-entregras e entrega Final:	 
Trabalho pratico 1 - Torniquete: Entrega termina o prazo no dia 25 de Outubro de 2018 as 23:59 
Engenharia de Software-MI1N - 1819SI

Trabalho prático 2 - Analise de requisitos: Entrega termina o prazo no dia 15 Novembro de 2018 as 23:59
Engenharia de Software-MI1N - 1819SI

Trabalho prático 2 - Relatorio de projecto: Entrega termina o prazo no dia 14 Dezembro de 2018 as 23:59
Engenharia de Software-MI1N - 1819SI

Trabalho prático 2 - Prototipo: Entrega termina o prazo no dia 22 Dezembro de 2018 as 23:59
Engenharia de Software-MI1N - 1819SI


== Funcionalidades 

As principais Funcionalidades do Sistema de Gestão de Projetos de Financiamentos(SGPF):

a. Aceitação de candidatura;
b. Abertura de projecto;
c. Parecer técnico;
d. Despacho da comissão de financiamento;
e. Suspensão de projecto;
f. Reactivação de projecto;
g. Reforço de projecto;
h. Realização de pagamento;
i. Alteração de dados de projecto;
j. Relatorio de informação de projecto;
k. Relatorio de pagamentos por projecto;


== Atores:
     Tecnico - {}
     Gestor de financiamento{}
     Comissao de financiamento{}

== Tipos de diagramas UML
	FUNCIONALIDADES
		- Diagramas de Casos de Utilização

	INTERACÃO
		- Diagramas de Sequência
		- Diagramas de Comunicação
		- Diagramas Temporais(Timing Diagrams)
		- Diagramas de Enquadramento de Interação (Interaction Overview Diagrams)
	
	ESTRUTURA
		- Diagramas de Classes
		- Diagramas de Objetos
		- Diagramas de Estrutura Composta

	DINAMICA
		- Diagramas de Transição de Estados
		- Diagramas de atividades

	IMPLEMENTAÇÃO
		- Diagramas de componentes

	AMBIENTE
		- Diagramas de Implantação

	ORGANIZAÇÃO
		- Diagramas de Pacotes(Package Diagrams)


== Tutoriais:

* Engenharia de Software - Rational Unified Process (RUP)
	Link -> https://www.youtube.com/watch?v=5CwEqJB3c5g